---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluespace-os
# description will be included in the image's metadata
description: Bluefin-based atomic OS for makerspaces.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: modules/tuxedo-drivers.yml

  - from-file: modules/3d-printing.yml
  - from-file: modules/audio.yml
  - from-file: modules/communication.yml
  - from-file: modules/laser.yml
  - from-file: modules/learning.yml
  - from-file: modules/modeling.yml
  - from-file: modules/office.yml
  - from-file: modules/password.yml
  - from-file: modules/photo-video.yml
  - from-file: modules/programming.yml
  - from-file: modules/tools.yml
  - from-file: modules/virtualization.yml
  - from-file: modules/web-browser.yml

  - type: os-release
    properties:
      NAME: bluespace-os
      PRETTY_NAME: bluespace-os
      ID: bluespace-os
      DEFAULT_HOSTNAME: blueplanet
      HOME_URL: https://github.com/Igami/bluespace-os
      DOCUMENTATION_URL: https://blue-build.org/reference/recipe/

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
